// Public keys that may sign releases (base64 SPKI DER, Ed25519). Generated by
// `npm run signing-key`; the private half lives only in the owner's password
// manager. Two entries are allowed while moving to a new key.
export const UPDATE_PUBLIC_KEYS: string[] = [
  "MCowBQYDK2VwAyEAW9jWs6sVvksOWS3fK9JWlMy73eFlXHkWcA9Zokpi80o=",
];
